version: '3'

services:

  db:

    container_name: db_postgres_container

    image: postgres:latest

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    restart: always

    networks:
      - my_network

  backend:

    container_name: backend_spring_boot_container

    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      - db

    networks:
      - my_network
  

  frontend:

    container_name: frontend_react_container
  
    build: 
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"


networks:
  my_network:
    driver: bridge

