version: '3'

services:

  db:

    container_name: postgres-container

    image: postgres:latest

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    restart: always

    networks:
      - my_network

  backend:

    container_name: backend_container

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - db

    networks:
      - my_network

networks:
  my_network:
    driver: bridge

